# Generated by Django 2.0.9 on 2018-10-02 10:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=16)),
                ('middlename', models.CharField(blank=True, max_length=16)),
                ('lastname', models.CharField(max_length=16)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 10, 2, 10, 44, 29, 541949, tzinfo=utc))),
                ('last_login', models.DateTimeField(default=datetime.datetime(2018, 10, 2, 10, 44, 29, 541975, tzinfo=utc))),
                ('birthday', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
