# Generated by Django 2.0.9 on 2018-10-02 11:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ip_adress',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AlterField(
            model_name='character',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 2, 11, 22, 15, 180153, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='character',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 2, 11, 22, 15, 180181, tzinfo=utc)),
        ),
    ]
