# Generated by Django 2.0.9 on 2018-10-02 21:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usermanagement', '0003_auto_20181002_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='active_Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 2, 21, 48, 42, 874125, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='character',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 2, 21, 48, 42, 874153, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='active_character',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.Character'),
        ),
        migrations.AddField(
            model_name='active_character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
