# Generated by Django 2.0.9 on 2018-10-02 23:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_auto_20181003_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='jobs',
            field=models.CharField(choices=[('HM', 'Headmaster'), ('MM', 'Management'), ('PT', 'Plot'), ('NU', 'Normal User')], default='NU', max_length=2),
        ),
        migrations.AlterField(
            model_name='character',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 2, 23, 18, 1, 442033, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='character',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 2, 23, 18, 1, 442057, tzinfo=utc)),
        ),
    ]
